# Generated by Django 5.1.4 on 2024-12-09 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_ago',
        ),
        migrations.AddField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
