# Generated by Django 5.1.4 on 2024-12-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_govt_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_type',
            field=models.CharField(default='jpg', max_length=200),
        ),
    ]
