# Generated by Django 5.1.4 on 2024-12-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBack',
            new_name='ContactUs',
        ),
    ]
